# Generated by Django 5.2.14 on 2026-05-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreathingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('inhale_seconds', models.PositiveIntegerField()),
                ('hold_seconds', models.PositiveIntegerField()),
                ('exhale_seconds', models.PositiveIntegerField()),
                ('repeat_count', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
